[build]
command = "yarn run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[context.development.environment]
SUPABASE_URL = 'https://alvewheipoqcathxuqah.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsdmV3aGVpcG9xY2F0aHh1cWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTIyOTg1MzcsImV4cCI6MjAyNzg3NDUzN30.yktBbpPcPe9Sy_k43pz9PYz2WIHvRzcJAUbxtaS27Ms'

[build.environment]
SUPABASE_URL = 'https://alvewheipoqcathxuqah.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsdmV3aGVpcG9xY2F0aHh1cWFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTIyOTg1MzcsImV4cCI6MjAyNzg3NDUzN30.yktBbpPcPe9Sy_k43pz9PYz2WIHvRzcJAUbxtaS27Ms'